using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace KompassHR.Areas.Module.Models.Module_Preboarding
{
    public class Preboarding_Mas_Employee
    {
        public double FID { get; set; }
        public string FID_Encrypted { get; set; }
        public bool Deactivate { get; set; }
        public bool UseBy { get; set; }
        public string CreatedBy { get; set; }
        public DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedDate { get; set; }
        public string MachineName { get; set; }
        public double EmployeeId { get; set; }
        public double CmpId { get; set; }
        public double BranchID { get; set; }
        public double DocNo { get; set; }
        public DateTime DocDate { get; set; }
        public string SalutationName { get; set; }
        public string EmployeeName { get; set; }
        public string BirthdayDate { get; set; }
        public string BirthdayPlace { get; set; }
        public double BirthdayProofOfDocumentID { get; set; }
        public string BirthdayProofOfCertificateNo { get; set; }
        public string Gender { get; set; }
        public bool GenderNotDisclose { get; set; }
        public string BloodGroup { get; set; }
        public string MaritalStatus { get; set; }
        public string AnniversryDate { get; set; }
        public double EmployeeReligionID { get; set; }
        public double EmployeeCasteID { get; set; }
        public bool CastNotDisclose { get; set; }
        public string EmployeeSubCategory { get; set; }
        public string PhysicalDisable { get; set; }
        public string PhysicalDisableType { get; set; }
        public string PhysicalDisableRemark { get; set; }
        public string IdentificationMark { get; set; }
        public double EmployeeQualificationID { get; set; }
        public string QualificationRemark { get; set; }
        public string Mobile1 { get; set; }
        public string Mobile2 { get; set; }
        public string WhatsAppNo { get; set; }
        public string PersonalEmailID { get; set; }
        public bool EmpNRI { get; set; }
        public string DrivingLicenceNo { get; set; }
        public DateTime DrivingExpiryDate { get; set; }
        public string PassportNo { get; set; }
        public string PresentPin { get; set; }
        public string PresentState { get; set; }
        public string PresentDistrict { get; set; }
        public string PresentTaluk { get; set; }
        public string PresentPO { get; set; }
        public string PresentCity { get; set; }
        public string PresentOther { get; set; }
        public string PermanentPin { get; set; }
        public string PermanentState { get; set; }
        public string PermanentDistrict { get; set; }
        public string PermanentTaluk { get; set; }
        public string PermanentPO { get; set; }
        public string PermanentCity { get; set; }
        public string PermanentOther { get; set; }
        public string NeighboursName1 { get; set; }
        public string NeighboursMobile1 { get; set; }
        public string NeighboursName2 { get; set; }
        public string NeighboursMobile2 { get; set; }
        public string RelativeName { get; set; }
        public string RelativeRelation { get; set; }
        public string RelativeMobile { get; set; }
        public string EmergencyName1 { get; set; }
        public string EmergencyRelation1 { get; set; }
        public string EmergencyMobile1 { get; set; }
        public string EmergencyName2 { get; set; }
        public string EmergencyRelation2 { get; set; }
        public string EmergencyMobile2 { get; set; }
        public string CompanyRefName1 { get; set; }
        public string CompanyRefMobile1 { get; set; }
        public string CompanyRefName2 { get; set; }
        public string CompanyRefMobile2 { get; set; }
        public string IFSCCode { get; set; }
        public string BankName { get; set; }
        public string AccountNo { get; set; }
        public string BankDetail { get; set; }
        public string BankBranchName { get; set; }
        public string NameAsPerBank { get; set; }
        public string PanNo { get; set; }
        public string NameAsPerPan { get; set; }
        public string AadhaarNo { get; set; }
        public string NameAsPerAadhaar { get; set; }
        public bool PANAadhaarLink { get; set; }
        public bool AadhaarNoMobileNoLink { get; set; }
        public string AadhaarNoMobileNo { get; set; }
        public double EmployeeDepartmentId { get; set; }
        public double EmployeeDesignationId { get; set; }
        public double EmployeeGradeID { get; set; }
        public string JoiningDate { get; set; }
        public double? ESIC_Insurance { get; set; }
        public bool? EM_ESI_Applicable { get; set; }
        public string EM_ESINO { get; set; }
        public bool? EM_PF_Applicable { get; set; }
        public bool EM_PF_Limit { get; set; }
        public bool EM_PF_EPS { get; set; }
        public string EM_PF_MobileNo { get; set; }
        public string EM_PF_BankName { get; set; }
        public string EM_PF_BankIFSC { get; set; }
        public string EM_PF_Account { get; set; }
        public string EM_PF_ExitDate { get; set; }
        public string EM_PF_CertificateNo { get; set; }
        public string EM_PF_PPO { get; set; }
        public string EM_PF_Opting { get; set; }
        public string EM_PF_VPF { get; set; }
        public string EM_FSType { get; set; }
        public string EM_FS_Name { get; set; }
        public string EM_PF_UAN { get; set; }
        public string EM_PF_NO { get; set; }
        public string EM_PF_RELATION { get; set; }
        public string EM_FNAME { get; set; }
        public DateTime EM_Nom_DOB { get; set; }
        public string EM_PF_Share { get; set; }
        public string EM_PF_Address { get; set; }
        public double ReportingHR { get; set; }
        public string EssloginID { get; set; }
        public string Esspassword { get; set; }
        public bool ESSActivateFlag { get; set; }
        public double ESSLoginAttemptCount { get; set; }
        public string Photo { get; set; }
        public bool EM_OldUANNo { get; set; }
        public bool EM_LinkWithUAN { get; set; }
        public bool EM_OldESICNo { get; set; }
        public bool EM_LinkWithESIC { get; set; }
        public string EM_PF_RELETION2 { get; set; }
        public string EM_RelationNAME2 { get; set; }
        public string EM_Nom_DOB2 { get; set; }
        public string EM_PF_Share2 { get; set; }
        public string EM_PF_Address2 { get; set; }
        public string EM_GuardianName2 { get; set; }
        public string EM_PF_RELETION3 { get; set; }
        public string EM_RelationNAME3 { get; set; }
        public string EM_Nom_DOB3 { get; set; }
        public string EM_PF_Share3 { get; set; }
        public string EM_PF_Address3 { get; set; }
        public string EM_GuardianName3 { get; set; }
        public string oldPFCode { get; set; }
        public bool ESSSendLink { get; set; }
        public string ESSSendDateTime { get; set; }
        public bool PreboardSubmit { get; set; }
        public DateTime PreboardSubmitDate { get; set; }
        public bool PreboardApproveRejectStatus { get; set; }
        public double PreboardApproveRejectBy { get; set; }
        public DateTime PreboardApproveRejectStatusDate { get; set; }
        public string PreboardRejectRemark { get; set; }
        public bool IsPersonalInfo { get; set; }
        public bool IsAddress { get; set; }
        public bool IsReference { get; set; }
        public bool IsBankpanaadhar { get; set; }
        public bool IsStatutory { get; set; }
        public bool IsFamilyInfo { get; set; }
        public bool IsQualification { get; set; }
        public bool IsPreviousEmployer { get; set; }
        public bool IsSKills { get; set; }
        public bool IsLanguage { get; set; }
        public bool IsPhoto { get; set; }
        public bool IsSignature { get; set; }
        public bool IsOther { get; set; }
        public DateTime LinkExpiryDate { get; set; }
        public bool FileUpload { get; set; }
        public DateTime PassportExpiryDate { get; set; }
        public string ReferenceNo { get; set; }
        public string Hobbies { get; set; }
        public float Height { get; set; }
        public float Weight { get; set; }
        public string MedDescription { get; set; }
        public string HospitalAddress { get; set; }
        public string PhysicianName { get; set; }
        public string HospitalContactNo { get; set; }
        public string NickName { get; set; }
        public string FavouriteColor { get; set; }
        public string FavouriteMovie { get; set; }
        public string FavouriteActor { get; set; }
        public string FavouriteGame { get; set; }
        public string FavouriteSong { get; set; }
        public string FavouriteFood { get; set; }
        public string FavouritePlace { get; set; }
        public string FavouriteDreamCar { get; set; }
        public string AboutYourself { get; set; }
        public string Extracurricular { get; set; }
        public string EyeNo { get; set; }
        public string LuckNo { get; set; }
        public string UploadSignature { get; set; }
        public string EM_GuardianName { get; set; }
        public int ValidDays { get; set; }
        public bool PermanentAddressSameAsCurrentAddress { get; set; }
        public string Verify_Personal_Status { get; set; }
        public DateTime verify_Personal_Date { get; set; }
        public string verify_Personal_Employeeid { get; set; }
        public string verify_Personal_RejectRemark { get; set; }
        public string Verify_Address_Status { get; set; }
        public DateTime Verify_Address_Date { get; set; }
        public string Verify_Address_Employeeid { get; set; }
        public string verify_Address_RejectRemark { get; set; }
        public string Verify_References_Status { get; set; }
        public DateTime Verify_References_Date { get; set; }
        public string Verify_References_Employeeid { get; set; }
        public string verify_References_RejectRemark { get; set; }
        public string Verify_Bank_Status { get; set; }
        public DateTime Verify_Bank_Date { get; set; }
        public string Verify_Bank_Employeeid { get; set; }
        public string verify_Bank_RejectRemark { get; set; }
        public string Verify_Family_Status { get; set; }
        public DateTime Verify_Family_Date { get; set; }
        public string Verify_Family_Employeeid { get; set; }
        public string verify_Family_RejectRemark { get; set; }
        public string Verify_Qualification_Status { get; set; }
        public DateTime Verify_Qualification_Date { get; set; }
        public string Verify_Qualification_Employeeid { get; set; }
        public string verify_Qualification_RejectRemark { get; set; }
        public string Verify_Document_Status { get; set; }
        public DateTime Verify_Document_Date { get; set; }
        public string Verify_Document_Employeeid { get; set; }
        public string verify_Document_RejectRemark { get; set; }
        public string Verify_Photo_Status { get; set; }
        public DateTime Verify_Photo_Date { get; set; }
        public string Verify_Photo_Employeeid { get; set; }
        public string verify_Photo_RejectRemark { get; set; }
        public string Verify_Signature_Status { get; set; }
        public DateTime Verify_Signature_Date { get; set; }
        public string Verify_Signature_Employeeid { get; set; }
        public string verify_Signature_RejectRemark { get; set; }
        public string Verify_PreEmployer_Status { get; set; }
        public DateTime Verify_PreEmployer_Date { get; set; }
        public string Verify_PreEmployer_Employeeid { get; set; }
        public string verify_PreEmployer_RejectRemark { get; set; }
        public string Verify_Skill_Status { get; set; }
        public DateTime Verify_Skill_Date { get; set; }
        public string Verify_Skill_Employeeid { get; set; }
        public string verify_Skill_RejectRemark { get; set; }
        public string Verify_Language_Status { get; set; }
        public DateTime Verify_Language_Date { get; set; }
        public string Verify_Language_Employeeid { get; set; }
        public string Verify_Language_RejectRemark { get; set; }
        public string Verify_Other_Status { get; set; }
        public DateTime Verify_Other_Date { get; set; }
        public string Verify_Other_Employeeid { get; set; }
        public string verify_Other_RejectRemark { get; set; }
        public string Verify_FinalApproval_Status { get; set; }
        public string Verify_FinalApproval_Employeeid { get; set; }
        public string Verify_Statutory_Status { get; set; }
        public DateTime Verify_Statutory_Date { get; set; }
        public string Verify_Statutory_Employeeid { get; set; }
        public string Verify_Statutory_RejectRemark { get; set; }
        public string Verify_FinalApproval_RejectRemark { get; set; }

        public string DesignationName { get; set; }
        public string DepartmentName { get; set; }

        public string Origin { get; set; }
        public int CompulsoryModuleId { get; set; }

    }
}